运算

In [1]:
from mxnet import nd

In [2]:
x=nd.arange(12).reshape(3,4)
x


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [3]:
nd.random.normal(0,1,(3,4))


[[ 1.1630785   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.558071   -0.5459446  -2.3556297 ]
 [ 0.54144025  2.6785064   1.2546344  -0.54877406]]
<NDArray 3x4 @cpu(0)>

In [5]:
x.exp()


[[1.0000000e+00 2.7182817e+00 7.3890562e+00 2.0085537e+01]
 [5.4598148e+01 1.4841316e+02 4.0342880e+02 1.0966332e+03]
 [2.9809580e+03 8.1030840e+03 2.2026465e+04 5.9874141e+04]]
<NDArray 3x4 @cpu(0)>

广播

In [6]:
import numpy as np
P=np.ones((2,3))
D=nd.array(P)
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [7]:
D.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

自动求梯度

In [8]:
from mxnet import autograd,nd

In [9]:
x=nd.arange(4).reshape(4,1)
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [10]:
x.attach_grad()

In [11]:
with autograd.record():
    y=2*nd.dot(x.T,x)

In [12]:
y.backward()

In [19]:
assert(x.grad-4*x).norm().asscalar()==0

4 * x：

这是预期的梯度值。假设你有一个损失函数，其梯度计算结果是 4 * x。

x.grad - 4 * x：

计算实际梯度与预期梯度之间的差值。

.norm()：

计算差值的范数（默认是 L2 范数）。范数表示差值的大小。

.asscalar()：

将范数从 mxnet.ndarray.NDArray 类型转换为 Python 标量（float 或 int）。

In [15]:
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

梯度是损失函数对模型参数的偏导数，它指示了参数应该如何更新以最小化损失函数。

训练模式和预测模式

In [20]:
print(autograd.is_training())

False


In [21]:
with autograd.record():
    print(autograd.is_training())

True
